import { redis, reddit } from '@devvit/web/server';
import type { OnModMailRequest } from '@devvit/web/shared';
import { logger, logZSet } from '../logger';
import type { PostId } from '../types';

const log = logger('appeal');
const APPEAL_LOG_KEY = 'bot:appeal:log';
const APPEAL_LOG_MAX = 200;
const APPEAL_TTL_SECONDS = 30 * 24 * 60 * 60;

type AppealState = 'pending' | 'removed';

export interface AppealRecord {
  authorName: string;
  postTitle: string;
  postUrl: string;
  subredditName: string;
  startedAt: number;
  state: AppealState;
}

export function appealKey(postId: string): string {
  return `appeal:post:${postId}`;
}

// Called from saved-responses.ts when "lock and start appeal" is chosen.
// Locks the post, creates an appeal record, and sends OP instructions via modmail.
// OP replies with `!remove` to remove the post; run() below handles the reply.
export async function startAppeal(targetId: string): Promise<void> {
  const post = await reddit.getPostById(targetId as PostId);
  const { subredditName, authorName } = post;

  await post.lock();

  const record: AppealRecord = {
    authorName,
    postTitle: post.title,
    postUrl: post.url,
    subredditName,
    startedAt: Date.now(),
    state: 'pending',
  };
  await redis.set(appealKey(targetId), JSON.stringify(record));
  await redis.expire(appealKey(targetId), APPEAL_TTL_SECONDS);

  await reddit.modMail.createConversation({
    subredditName,
    subject: 'Your post has been locked',
    body: [
      `Your [post](${post.url}) has been locked pending review.`,
      '',
      'To remove your post, reply to this message with: `!remove`',
      '',
      'Your appeal window expires in 30 days.',
    ].join('\n'),
    to: `u/${authorName}`,
  });

  await logZSet(APPEAL_LOG_KEY, { action: 'appeal_start', postId: targetId, authorName }, APPEAL_LOG_MAX);
  log.info('Appeal started', { postId: targetId, authorName });
}

// MOD_MAIL trigger: handles `!remove` replies from the appeal modmail conversation.
export async function run(event: OnModMailRequest): Promise<void> {
  if (event.conversationType !== 'sr_user') return;
  if (event.isAutoGenerated) return;

  const conversationId = event.conversationId;
  const senderName = event.messageAuthor?.name ?? '';
  if (!senderName) return;

  let firstBody: string;
  let latestBody: string;
  try {
    const { conversation } = await reddit.modMail.getConversation({ conversationId });
    if (conversation?.subject !== 'Your post has been locked') return;
    const sorted = Object.values(conversation?.messages ?? {})
      .sort((a, b) => new Date(a.date ?? 0).getTime() - new Date(b.date ?? 0).getTime());
    firstBody  = sorted[0]?.body ?? '';
    latestBody = sorted[sorted.length - 1]?.body?.trim() ?? '';
  } catch (err) {
    log.warn('Could not fetch modmail conversation', { conversationId, error: (err as Error).message });
    return;
  }

  if (latestBody !== '!remove') return;

  // Post URL is always in the first message as [post](<url>); extract the id from the path
  const urlMatch = firstBody.match(/\[post\]\(https?:\/\/[^)]*\/comments\/([a-z0-9]+)\//i);
  if (!urlMatch) return;
  const postId = `t3_${urlMatch[1]}`;
  const key = appealKey(postId);

  const raw = await redis.get(key);
  if (!raw) {
    await reply(conversationId, 'No active appeal found for this post.');
    return;
  }

  const record: AppealRecord = JSON.parse(raw);

  if (record.state !== 'pending') {
    await reply(conversationId, 'This appeal has already been resolved.');
    return;
  }

  if (senderName !== record.authorName) {
    await reply(conversationId, 'Only the post author can use this appeal link.');
    return;
  }

  try {
    await reddit.remove(postId as PostId, false);
  } catch (err) {
    log.warn('Could not remove post', { postId, error: (err as Error).message });
    await reply(conversationId, 'Failed to remove the post. Please contact the mods directly.');
    return;
  }
  record.state = 'removed';
  await redis.set(key, JSON.stringify(record));
  await reply(conversationId, 'Thanks!');
  try {
    await reddit.modMail.archiveConversation(conversationId);
  } catch (err) {
    log.warn('Could not archive conversation', { conversationId, error: (err as Error).message });
  }
  await logZSet(APPEAL_LOG_KEY, { action: 'appeal_delete', postId, by: senderName }, APPEAL_LOG_MAX);
  log.info('Appeal: post removed', { postId, by: senderName });
}

async function reply(conversationId: string, body: string): Promise<void> {
  try {
    await reddit.modMail.reply({ conversationId, body });
  } catch (err) {
    log.warn('Could not reply to modmail', { conversationId, error: (err as Error).message });
  }
}
