import { redis, reddit } from '@devvit/web/server';
import type { OnModMailRequest } from '@devvit/web/shared';
import { logger, logZSet } from '../logger';
import type { PostId } from '../types';
import { type AppealRecord, appealKey } from '../action-modules/appeal';

const log = logger('appeal-moderator');
const APPEAL_LOG_KEY = 'bot:appeal:log';
const APPEAL_LOG_MAX = 200;

export async function run(event: OnModMailRequest): Promise<void> {
  if (event.conversationType !== 'sr_user') return;
  if (event.isAutoGenerated) return;

  const conversationId = event.conversationId;
  const senderName = event.messageAuthor?.name ?? '';
  if (!senderName) return;

  let firstBody: string;
  let latestBody: string;
  try {
    const { conversation } = await reddit.modMail.getConversation({ conversationId });
    if (conversation?.subject !== 'Your post has been locked') return;
    const sorted = Object.values(conversation?.messages ?? {})
      .sort((a, b) => new Date(a.date ?? 0).getTime() - new Date(b.date ?? 0).getTime());
    firstBody  = sorted[0]?.body ?? '';
    latestBody = sorted[sorted.length - 1]?.body?.trim() ?? '';
  } catch (err) {
    log.warn('Could not fetch modmail conversation', { conversationId, error: (err as Error).message });
    return;
  }

  if (latestBody !== '!remove') return;

  // Post URL is always in the first message as [post](<url>); extract the id36 from the path
  const urlMatch = firstBody.match(/\[post\]\(https?:\/\/[^)]*\/comments\/([a-z0-9]+)\//i);
  if (!urlMatch) return;
  const postId = `t3_${urlMatch[1]}`;
  const key = appealKey(postId);

  const raw = await redis.get(key);
  if (!raw) {
    await reply(conversationId, 'No active appeal found for this post.');
    return;
  }

  const record: AppealRecord = JSON.parse(raw);

  if (record.state !== 'pending') {
    await reply(conversationId, 'This appeal has already been resolved.');
    return;
  }

  if (senderName !== record.authorName) {
    await reply(conversationId, 'Only the post author can use this appeal link.');
    return;
  }

  try {
    await reddit.remove(postId as PostId, false);
  } catch (err) {
    log.warn('Could not remove post', { postId, error: (err as Error).message });
    await reply(conversationId, 'Failed to remove the post. Please contact the mods directly.');
    return;
  }
  record.state = 'removed';
  await redis.set(key, JSON.stringify(record));
  await reply(conversationId, 'Thanks!');
  try {
    await reddit.modMail.archiveConversation(conversationId);
  } catch (err) {
    log.warn('Could not archive conversation', { conversationId, error: (err as Error).message });
  }
  await logZSet(APPEAL_LOG_KEY, { action: 'appeal_delete', postId, by: senderName }, APPEAL_LOG_MAX);
  log.info('Appeal: post removed', { postId, by: senderName });
}

async function reply(conversationId: string, body: string): Promise<void> {
  try {
    await reddit.modMail.reply({ conversationId, body });
  } catch (err) {
    log.warn('Could not reply to modmail', { conversationId, error: (err as Error).message });
  }
}
